// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYFNjsQM8aAa762nU6JTvhd7SAOtiQE60',
    appId: '1:351456687609:web:eb936dfe56ab8f29423928',
    messagingSenderId: '351456687609',
    projectId: 'flashchat-ff443',
    authDomain: 'flashchat-ff443.firebaseapp.com',
    storageBucket: 'flashchat-ff443.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwR_3K2gePsNLxFfxvOUp0Da7J97xz1NE',
    appId: '1:351456687609:android:ad383bc4279360f1423928',
    messagingSenderId: '351456687609',
    projectId: 'flashchat-ff443',
    storageBucket: 'flashchat-ff443.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjDWxF2W8hkN1XBz8iQZjD4tTfXdI-bOk',
    appId: '1:351456687609:ios:868f966ae3d8b164423928',
    messagingSenderId: '351456687609',
    projectId: 'flashchat-ff443',
    storageBucket: 'flashchat-ff443.appspot.com',
    iosBundleId: 'com.example.fulutterFlashchatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjDWxF2W8hkN1XBz8iQZjD4tTfXdI-bOk',
    appId: '1:351456687609:ios:92e05f843703e3a9423928',
    messagingSenderId: '351456687609',
    projectId: 'flashchat-ff443',
    storageBucket: 'flashchat-ff443.appspot.com',
    iosBundleId: 'com.example.fulutterFlashchatApp.RunnerTests',
  );
}
